[project]
name = "ting13"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "botasaurus>=4.0.74",
    "chrome-extension-python>=1.0.1",
    "pathvalidate>=3.2.1",
    "typer>=0.12.5",
]
